name: acquisitions-dev

services:
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: neon-local
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    healthcheck:
      test: ['CMD', 'bash', '-lc', '</dev/tcp/127.0.0.1/5432']
      interval: 10s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      target: dev
    container_name: acquisitions-app-dev
    env_file:
      - .env.development
    depends_on:
      - neon-local
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
# Compose reads environment variables from the specified files
# See .env.development for required values
