name: Lint and Format

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier check
        run: npm run format:check

      - name: Summary and suggestions
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ ESLint and Prettier checks passed." >> "$GITHUB_STEP_SUMMARY"
          else
            echo "❌ Lint/format issues detected." >> "$GITHUB_STEP_SUMMARY"
            echo "" >> "$GITHUB_STEP_SUMMARY"
            echo "Fix locally with:" >> "$GITHUB_STEP_SUMMARY"
            echo "  npm run lint:fix" >> "$GITHUB_STEP_SUMMARY"
            echo "  npm run format" >> "$GITHUB_STEP_SUMMARY"
            echo "::error::ESLint/Prettier found issues. Run 'npm run lint:fix' and 'npm run format' locally to resolve." 
          fi
